# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

mod_version=12.0.0-beta+26.3
maven_group=dev.shadowhunter22
archives_base_name=shadowhunter22s-config-library

minecraft_version=26.3-snapshot-7
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.156.3+26.3