# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

mod_version=11.0.0+26.2
maven_group=dev.shadowhunter22
archives_base_name=shadowhunter22s-config-library

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.152.1+26.2