# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

mod_version=11.0.0-beta+26.2
maven_group=dev.shadowhunter22
archives_base_name=shadowhunter22s-config-library

minecraft_version=26.2-rc-1
loader_version=0.19.3
loom_version=1.16-SNAPSHOT
fabric_api_version=0.152.0+26.2